# Base configs
baseurl: "https://amguillotin.github.io/photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Photography by Alexis Guillotin"
subtitle: "See the world through my eyes!"
author: "Alexis Guillotin"
header:
 title: "Photography"
 subtitle: "by Alexis Guillotin"
footer:
 name: "Hey there, my name is Alexis"
 bio: "I am a developer and a tech aficionado from France. Love making teeny tiny apps solving tiny problems in life and now learning photography."
social_urls:
  linkedin: "https://www.linkedin.com/in/alexis-guillotin-50a8b8188/"
  github: "https://github.com/amguillotin"
